In [1]:
#We want to process given data using some ML algo, first we need to process the data to make it suitable to be processed
#First we clean the data
#Data cleaning involves - Handling null vales and Taking mean
#We use sci kit learn for Data Pre Processing 

In [2]:
#Create a folder with this notebook and the CleanupData.csv

In [3]:
import os
print(os.listdir())
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

['.ipynb_checkpoints', '911 Project', 'B2020037_Pranav Vikas Arora_CV.docx', 'B2020037_Pranav Vikas Arora_CV.pdf', 'Census', 'CleanupData.csv', 'Data Pre-processing (Imputation, Feature Scaling) using Sci Kit learn.ipynb', 'debug.log', 'desktop.ini', 'GitHub Desktop.lnk', 'Microsoft Teams.lnk', 'MongoDBCompass.lnk', 'Spotify.lnk', 'Vikas Arora', 'Zoom.lnk', '~$assignment anns.docx', '~$ta discription - Assignment 1.docx']


In [4]:
data = pd.read_csv('CleanupData.csv')

In [5]:
data

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes
5     Delhi  25.0        5800.0              Yes
6    Mumbai   NaN        5200.0               No
7     Delhi  38.0        7900.0              Yes
8  Banglore  40.0        8300.0               No
9     Delhi  27.0        6700.0              Yes

In [6]:
#Indexing for colms state being 0, age being 1, pocket money 2 and course purchased 3
#So state,age,pocketmoney are factors which influence the answer for course purchased
#Hence age,pocketmoney and state are independent variables
#Course purchased is dependent 
#x = data.iloc[row,colmn] hota hai
#if we write data.iloc[:,:-1] the -1 means that we do not want last colmn
x = data.iloc[:,:-1].values
x

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, nan],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', nan, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [7]:
y = data.iloc[:,3].values
y
#Only gives coln with index = 3 which is course purchased in this case 

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [8]:
#Data Imputation = Replacing NaNs with some values

In [9]:
import sklearn
#sklearn is Scikit learn

In [10]:
from sklearn.impute import SimpleImputer
#To perform imputation

In [11]:
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

In [12]:
#The Imputer fills missing values with some statistics (e.g. mean, median, ...) of the data. 
#To avoid data leakage during cross-validation, it computes the statistic on the train data during the fit, stores it and uses it on the test data, during the transform
#Cross validation explained : Learning the parameters of a prediction function and testing it on the same data is a methodological mistake: a model that would just repeat the labels of the samples that it has just seen would have a perfect score but would fail to predict anything useful on yet-unseen data. This situation is called overfitting. To avoid it, it is common practice when performing a (supervised) machine learning experiment to hold out part of the available data as a test set X_test, y_test.

In [13]:
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [14]:
x

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, 6377.777777777777],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', 28.77777777777778, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [15]:
#We have categorical data in colmns state so we will convert it into numbers for the computer to understand
#handle categorical data in our data
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x.fit_transform(x[:, 0])
x
#Giving numeric labels to categorical data

array([[1, 34.0, 7200.0],
       [2, 17.0, 4800.0],
       [0, 20.0, 5400.0],
       [2, 28.0, 6100.0],
       [0, 30.0, 6377.777777777777],
       [1, 25.0, 5800.0],
       [2, 28.77777777777778, 5200.0],
       [1, 38.0, 7900.0],
       [0, 40.0, 8300.0],
       [1, 27.0, 6700.0]], dtype=object)

In [16]:
#So now we can see that delhi is 1, mumbai is 2, and banaglore is 0

In [17]:
#Now these values 0,1,2 are mathematical but we can make it easier for computer by performing one hot encoding
#In one hot encoding we will for a dummy matrix
#So if the dummy matrix wants to represent Delhi ...and the order of matrix colmns is Delhi Mumbai Bangalore
#then the matrix values will be 1 0 0
#Similarly if u want to represent Mumbai in the same dummy matrix
#it will be 0 1 0
#This above dummy matrix represntation of categorical data is caled one hot encoding

In [18]:
#create dummy matrix for categorical dataset
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder()
x = onehotencoder.fit_transform(x).toarray()
np.set_printoptions(suppress=True)
x

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0.,

In [19]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [20]:
#handle y matrix for categorical data
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [21]:
#prepare test and training data set
# split our data into 2 parts, one will be training and other will be test
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [23]:
#x consists of all independent variables now and we have created a training and testing data set for x
#similary y contains course taken (dependent) and we have created a training and testing data set for y
#Now we can train using x and y 

In [25]:
x_train

array([[1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0.]])

In [26]:
x_test

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0.]])

In [27]:
y_train

array([0, 1, 0, 1, 1, 0, 0, 0])

In [28]:
y_test

array([1, 1])

In [29]:
#For scaling the features we use Standard Scaler from sklearn.preprocessing library
#from sklearn.preprocessing import Standard Scaler
#scale_x = StandardScaler()
#x_train = scale_x.fir_transform(x_train)
#x_test = scale_x.transform(x_test)