In [5]:
#Numpy - To work on and create arrays, matrices. Has fns like normal dist, gaussian dist, etc.
#importing the library
import numpy as np
mylist = [1,2,3,4,5]
#To get one dim array from list
myonedimarray = np.array(mylist)
print(myonedimarray)

[1 2 3 4 5]


In [6]:
#To get multi dim array from list
multi_list = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
mymultidimarray = np.array(multi_list)
print(mymultidimarray)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
np.arange(0,10)
#Last no is not included

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)
#Giving a gap of 2 after each element in the sequence

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [11]:
np.zeros((4,4))
#4*4 matrix will all elements being 0s

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.linspace(0,5,10)
#Plots values bet 0 and 5, and gives 10 equally spaced points bet 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
np.ones((4,4))
#4*4 matrix with all ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.identity(4,int)
#to get an identity matrix and we mention data type as well

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [18]:
np.random.randn()
#Randn gives normal distribution

-2.7692478951768638

In [22]:
np.random.randint(1,50)
#gives a random int bet 1 to 50

37

In [26]:
#To convert list to matrix
num = np.arange(25)
reshaped = num.reshape(5,5)
print(reshaped)
#In reshape if we put (4,4) we would get error, since there are 25 chars 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [27]:
#Position of array
myarray = np.arange(10,21)
myarray[0]

10

In [28]:
myarray[1:4]

array([11, 12, 13])

In [29]:
myarray[:4]
#All elements till the 4th one

array([10, 11, 12, 13])

In [30]:
myarray[4:]
#All elements from 4 onwards

array([14, 15, 16, 17, 18, 19, 20])

In [37]:
a = myarray[:4]
a

array([10, 11, 12, 13])

In [38]:
a[:]  =50

In [40]:
myarray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
#So since we saw above the array a affected myarray, therefore we use .copy() to create a copy of the array we dont want to dsitrub

In [41]:
twodim = np.array([[1,2,3],[3,4,5],[5,6,7]])
twodim[2][1]
#[2] got us the list indexed as no 2 and 1 got us the element from that list which is indexed as 1 

6

In [43]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#Conditional Returns
b>10

array([False, False, False, False, False, False, False, False])

In [47]:
b[b>1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
b*2
#All elements get multiplied by 2

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [49]:
b+b

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
np.sqrt(b)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        ])

In [51]:
np.mean(b)

5.5

In [52]:
np.std(b)

2.29128784747792